/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static negocio.cliente.ejecutarActualizar;


/**
 *
 * @author CEC
 */
public class actualizarcliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ingresarcliente
     */
    public actualizarcliente() {
        //Se inicializan los componentes para cargarlos
        initComponents();
        cargarComboTipoId();
        cargarComboPersoneria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CMBTIPOID = new javax.swing.JComboBox<>();
        LBLTIPOID = new javax.swing.JLabel();
        LBLID = new javax.swing.JLabel();
        TXTID = new javax.swing.JTextField();
        CMBPERSONERIA = new javax.swing.JComboBox<>();
        LBLPERSONERIA = new javax.swing.JLabel();
        LBLNOMBRE = new javax.swing.JLabel();
        LBLAPELLIDO = new javax.swing.JLabel();
        LBLDIRECCION = new javax.swing.JLabel();
        LBLTELEFONO = new javax.swing.JLabel();
        TXTNOMBRE = new javax.swing.JTextField();
        TXTAPELLIDO = new javax.swing.JTextField();
        TXTDIRECCION = new javax.swing.JTextField();
        TXTTELEFONO = new javax.swing.JTextField();
        BTNSALIR = new javax.swing.JButton();
        BTNGRABAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("INGRESO");

        CMBTIPOID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LBLTIPOID.setText("TIPO DE IDENTIFICACION");

        LBLID.setText("IDENTIFICACION");

        TXTID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTIDActionPerformed(evt);
            }
        });
        TXTID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTIDKeyTyped(evt);
            }
        });

        CMBPERSONERIA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LBLPERSONERIA.setText("TIPO DE PERSONERIA");

        LBLNOMBRE.setText("NOMBRES");

        LBLAPELLIDO.setText("APELLIDOS");

        LBLDIRECCION.setText("DIRECCION");

        LBLTELEFONO.setText("TELEFONO");

        TXTNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOMBREActionPerformed(evt);
            }
        });
        TXTNOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNOMBREKeyTyped(evt);
            }
        });

        TXTAPELLIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTAPELLIDOActionPerformed(evt);
            }
        });
        TXTAPELLIDO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTAPELLIDOKeyTyped(evt);
            }
        });

        TXTDIRECCION.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTDIRECCIONKeyTyped(evt);
            }
        });

        TXTTELEFONO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTTELEFONOKeyTyped(evt);
            }
        });

        BTNSALIR.setText("SALIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });

        BTNGRABAR.setText("GRABAR");
        BTNGRABAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGRABARActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("FORMULARIO DE ACTUALIZAR DE CLIENTES ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLTIPOID)
                            .addComponent(LBLID)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LBLTELEFONO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBLDIRECCION, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBLAPELLIDO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBLNOMBRE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBLPERSONERIA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BTNGRABAR, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CMBPERSONERIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CMBTIPOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTNOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(TXTAPELLIDO)
                            .addComponent(TXTDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTNSALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMBTIPOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLTIPOID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBLID)
                    .addComponent(TXTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMBPERSONERIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLPERSONERIA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTNOMBRE)
                    .addComponent(LBLNOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLAPELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLDIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBLTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNSALIR, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(BTNGRABAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTAPELLIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTAPELLIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTAPELLIDOActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        this.dispose();//cierra la instancia del hilo que maneja la ventana
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void TXTIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTIDKeyTyped
        // TODO add your handling code here: Valida la cantidad de caracteres que se teclean
        if (this.TXTID.getText().length() >= 20) {
            evt.consume();//De esta forma se bloquea el componente
        }
        //Validacion si no es un digito bloqueo
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TXTIDKeyTyped

    private void TXTNOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNOMBREKeyTyped
        // TODO add your handling code here: Valida la cantidad de caracteres que se teclean
        if (this.TXTNOMBRE.getText().length() >= 40) {
            evt.consume();//De esta forma se bloquea el componente
        }
        //Validacion si es un digito bloqueo
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TXTNOMBREKeyTyped

    private void TXTAPELLIDOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTAPELLIDOKeyTyped
        // TODO add your handling code here: Valida la cantidad de caracteres que se teclean
        if (this.TXTAPELLIDO.getText().length() >= 40) {
            evt.consume();//De esta forma se bloquea el componente
        }
        //Validacion si es un digito bloqueo
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TXTAPELLIDOKeyTyped

    private void TXTDIRECCIONKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTDIRECCIONKeyTyped
        // TODO add your handling code here: Valida la cantidad de caracteres que se teclean
        if (this.TXTDIRECCION.getText().length() >= 35) {
            evt.consume();//De esta forma se bloquea el componente
        }
        //Validacion si es un digito bloqueo
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TXTDIRECCIONKeyTyped

    private void TXTTELEFONOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTTELEFONOKeyTyped
        // TODO add your handling code here: Valida la cantidad de caracteres que se teclean
        if (this.TXTTELEFONO.getText().length() >= 20) {
            evt.consume();//De esta forma se bloquea el componente
        }   
        //Validacion si no es un digito bloqueo
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TXTTELEFONOKeyTyped

    private void TXTIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTIDActionPerformed

    private void TXTNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBREActionPerformed

    private void BTNGRABARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGRABARActionPerformed
        // TODO add your handling code here:
        if (this.validarDatos()) {
            try {
                String[] args = new String[7];
                //Selecciona el que se encuentra marcado
                args[0] = String.valueOf(this.CMBTIPOID.getSelectedItem());
                //Selecciona el texto del textfield
                args[1] = this.TXTID.getText();
                args[2] = String.valueOf(this.CMBPERSONERIA.getSelectedItem());
                args[3] = this.TXTNOMBRE.getText();
                args[4] = this.TXTAPELLIDO.getText();
                args[5] = this.TXTDIRECCION.getText();
                args[6] = this.TXTTELEFONO.getText();
                ejecutarActualizar(args);
                //Mensaje de informacion al realizar el ingreso
                JOptionPane.showMessageDialog(rootPane, "CLIENTE ACTUALIZADO EXITOSAMENTE", "INFORMACION", 1);
            } catch (SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(actualizarcliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //Mensaje de error debido a un ingreso incorrecto "2" advertencia
            JOptionPane.showMessageDialog(rootPane, "DATOS INCORRECTOS", "ERROR", 2);
        }
    }//GEN-LAST:event_BTNGRABARActionPerformed

    /**
     * Valida que tenga informacion cada campo 
     * @return Devuelve un mensaje demostrando la validacion de los datos
     */
    private boolean validarDatos(){
        boolean banderaValidadcion = true;
        if (this.TXTID.getText().trim().isEmpty()) {
            banderaValidadcion = false;
        }
        
        if (this.TXTNOMBRE.getText().trim().isEmpty()) {
            banderaValidadcion = false;
        }
        
        if (this.TXTAPELLIDO.getText().trim().isEmpty()) {
            banderaValidadcion = false;
        }
        
        if (this.TXTDIRECCION.getText().trim().isEmpty()) {
            banderaValidadcion = false;
        }
        
        return banderaValidadcion;
    }
    
    private void cargarComboTipoId(){
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        modeloCombo.addElement("CI");
        modeloCombo.addElement("RUC");
        modeloCombo.addElement("PAS");
        this.CMBTIPOID.setModel(modeloCombo);
    }
    
    private void cargarComboPersoneria(){
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        modeloCombo.addElement("N");
        modeloCombo.addElement("J");
        this.CMBPERSONERIA.setModel(modeloCombo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGRABAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JComboBox<String> CMBPERSONERIA;
    private javax.swing.JComboBox<String> CMBTIPOID;
    private javax.swing.JLabel LBLAPELLIDO;
    private javax.swing.JLabel LBLDIRECCION;
    private javax.swing.JLabel LBLID;
    private javax.swing.JLabel LBLNOMBRE;
    private javax.swing.JLabel LBLPERSONERIA;
    private javax.swing.JLabel LBLTELEFONO;
    private javax.swing.JLabel LBLTIPOID;
    private javax.swing.JTextField TXTAPELLIDO;
    private javax.swing.JTextField TXTDIRECCION;
    private javax.swing.JTextField TXTID;
    private javax.swing.JTextField TXTNOMBRE;
    private javax.swing.JTextField TXTTELEFONO;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
