/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static negocio.cliente.ejecutarConsulta;


/**
 *
 * @author CEC
 */
public class consultarcliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form ingresarcliente
     */
    public consultarcliente() {
        //Se inicializan los componentes para cargarlos
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLNOMBRE = new javax.swing.JLabel();
        TXTNOMBRE = new javax.swing.JTextField();
        BTNSALIR = new javax.swing.JButton();
        BTNGRABAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setTitle("INGRESO");

        LBLNOMBRE.setText("NOMBRES");

        TXTNOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTNOMBREActionPerformed(evt);
            }
        });
        TXTNOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTNOMBREKeyTyped(evt);
            }
        });

        BTNSALIR.setText("SALIR");
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });

        BTNGRABAR.setText("CONSULTAR");
        BTNGRABAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGRABARActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CONSULTA DE CLIENTES POR NOMBRES");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LBLNOMBRE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNGRABAR, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addGap(141, 141, 141)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TXTNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BTNSALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTNOMBRE)
                    .addComponent(LBLNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNSALIR, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(BTNGRABAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        // TODO add your handling code here:
        this.dispose();//cierra la instancia del hilo que maneja la ventana
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void TXTNOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTNOMBREKeyTyped
        // TODO add your handling code here: Valida la cantidad de caracteres que se teclean
        if (this.TXTNOMBRE.getText().length() >= 40) {
            evt.consume();//De esta forma se bloquea el componente
        }
        //Validacion si es un digito bloqueo
        if (Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_TXTNOMBREKeyTyped

    private void TXTNOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTNOMBREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTNOMBREActionPerformed

    private void BTNGRABARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGRABARActionPerformed
        // TODO add your handling code here:
        if (this.validarDatos()) {
                String args1 = new String();
                args1 = this.TXTNOMBRE.getText();
            try {
                String arr[] = new String[5];
                arr = ejecutarConsulta(args1);
                jTextArea1.insert(arr[4], 0);
                jTextArea1.insert(arr[3], 0);
                jTextArea1.insert(arr[2], 0);
                jTextArea1.insert(arr[1], 0);
                jTextArea1.insert(arr[0], 0);
            } catch (ClassNotFoundException | SQLException | InstantiationException | IllegalAccessException ex) {
                Logger.getLogger(consultarcliente.class.getName()).log(Level.SEVERE, null, ex);
            }
                //Mensaje de informacion al realizar el ingreso
                JOptionPane.showMessageDialog(rootPane, "CLIENTE CONSULTADO EXITOSAMENTE", "INFORMACION", 1);
            
        } else {
            //Mensaje de error debido a un ingreso incorrecto "2" advertencia
            JOptionPane.showMessageDialog(rootPane, "DATOS INCORRECTOS", "ERROR", 2);
        }
    }//GEN-LAST:event_BTNGRABARActionPerformed

    /**
     * Valida que tenga informacion cada campo 
     * @return Devuelve un mensaje demostrando la validacion de los datos
     */
    private boolean validarDatos(){
        boolean banderaValidadcion = true;
      
        
        if (this.TXTNOMBRE.getText().trim().isEmpty()) {
            banderaValidadcion = false;
        }
        
      
      
        return banderaValidadcion;
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNGRABAR;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JLabel LBLNOMBRE;
    private javax.swing.JTextField TXTNOMBRE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
